# Generated by Django 4.1.4 on 2024-01-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, verbose_name='nombres')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('pasaporte', models.CharField(max_length=60, verbose_name='Pasaporte')),
                ('apodo', models.CharField(max_length=20, verbose_name='apodo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Persona',
            },
        ),
    ]
