# Generated by Django 4.1.4 on 2024-01-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fechaLanzamiento'], 'verbose_name_plural': 'Libros'},
        ),
    ]
