# Generated by Django 4.1.4 on 2024-01-25 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libroLector', to='lector.lector'),
        ),
    ]
