# Generated by Django 4.1.4 on 2024-01-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0004_alter_prestamo_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libroPrestamo', to='lector.lector'),
        ),
    ]
