# Generated by Django 4.1.4 on 2024-01-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtraPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('pasaporte', models.CharField(max_length=50, verbose_name='pasaporte')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
                ('edad', models.PositiveBigIntegerField()),
                ('apodo', models.CharField(max_length=30, verbose_name='apodo')),
            ],
            options={
                'verbose_name': 'OtraPersona',
                'verbose_name_plural': 'OtraPersonas',
            },
        ),
    ]
