# Generated by Django 4.1.4 on 2024-01-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otrapersona',
            unique_together={('pais', 'apodo')},
        ),
        migrations.AddConstraint(
            model_name='otrapersona',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 5)), name='edadMayor'),
        ),
    ]
